# Generated by Django 4.2 on 2023-05-02 17:47

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_tags_alter_category_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='pid', unique=True),
        ),
    ]
